### ISSUE TITLE
为性能考虑，sqlite应换为mysql或postgresql

### ISSUE THREAD

**Issue by thuhole** [newthuhole/hole-backend#1]
https://github.com/newthuhole/hole-backend/blob/dbff5435933dc7ca50d42f393b9715e131738f0c/hole.py#L13

不然如果以后流量大了，很可能并发性能就不够了

**Comment by hole-thu** [comment]
树洞用户量非常有限（极限不过几万人），且由于服务器限制部署时候进程、线程数不会很大，总之不会有高并发。

在没有高并发、没有复杂查询语句的情况下，sqlite性能显著更好。

**Comment by thuhole** [comment]
几万人也不是小数字。如果用户多了之后出现热点事件，可能会承受1000QPS的查询量。
