### ISSUE TITLE
关于匿名性的质疑

### ISSUE THREAD

**Issue by thuhole** [newthuhole/hole-backend#2]
https://github.com/newthuhole/hole-backend/blob/dbff5435933dc7ca50d42f393b9715e131738f0c/config.sample.py#L8

在现在的代码中，可以看出newthuhole打算使用闭社实现登录验证。但是，闭社是实名社区，并且会[保留日志](https://thu.closed.social/terms)。

在我们无法确认newthuhole与闭社关系之前，没有任何方法确保newthuhole的作者是否有查看闭社注册信息的权限。

如果更进一步怀疑，newthuhole与闭社管理员也许有密切关系甚至是同一组织在维护。比如从[commit习惯](https://github.com/closed-social/askMe/commits/master)、代码风格来看，newthuhole与闭社管理员@OmmyZhang 都有相似之处。从公开的GitHub信息显示，@OmmyZhang 也对类似的匿名社区有着不少的兴趣和代码贡献。在有相同的兴趣爱好的前提下，有理由质疑相互认识、关系密切、或是同一人。

除此之外，一旦校方或其他权力机构同时对闭社和newthuhole进行身份查询和日志查询，或是与**校园网流量日志**进行对比，匿名性也无法保障。

另外一点考虑就是，虽然newthuhole使用AGPL v3 License，但我们仍然**无法从技术上或法律上约束实际后端代码与在GitHub公开的代码一致**。在newthuhole保持匿名存在的前提下，不用对任何信用上的损失负责。

如果一致，也**无法验证后端机器是否有额外的抓包日志记录工具**。实际上，就算是简单的IP地址日志，在校内也可以很精确的定位。

以上都是有待考虑的问题。匿名性与管理难度是相互矛盾的，希望newthuhole能做出合理取舍。

**Comment by hole-thu** [comment]
@thuhole 
1. 阅读代码可知，实现后台匿名主要是靠的用户任何行为（甚至关注和举报）都不会绑定到用户本身，而是记录一个name_hash，该name_hash基于每次重启服务会重置、仅保存在内存中的随机salt。使用闭社帐号而非清华邮箱注册保证了即使在“哪些人注册了树洞”这个问题上新T树洞也有大于等于T大树洞的匿名性。

2. 实际代码不一致、额外日志等问题，这个是用户很难验证的，只能由用户自己选择是否相信维护者。但不管怎么说，使用一个设计上比较安全的项目再去担心实际跑的代码不一致，也远好于使用一个设计上就直接不安全的项目。

3. 后台匿名和管理有一定的矛盾，但更多还是取决于设计者的重视程度和具体设计。

4. 风格上，某系的学生应该都用python写过后端，也都知道commit信息应该提供有意义内容。具体代码风格上，我是遵守的某种CodeStyle，所以也没什么好多说的了。如果还有疑问建议多读开源项目。其他人我不了解，但至少我是因为T大树洞才开始关注匿名平台的，之前没参与过匿名社交的项目。之后我不会回应关于作者身份的猜测了，并且由于树洞的性质，我认为公开进行这种猜测是不道德的。

**Comment by thuhole** [comment]
所以如你所说，**问题的关键还是在于用户是否相信维护者**。对于像你（们）这样有能力写出一整个树洞代码的人，**记录额外日志不存在任何技术困难，也不会带来很多额外成本，更无法被用户发现**。闭社账号也是和邮箱明文直接挂钩的，此issue就在指出这个问题。闭社刚刚曝出的[闭社使用未名BBS作CDN事件](https://bbs.pku.edu.cn/v2/post-read.php?bid=104&threadid=17779684)也让公众对闭社的信誉产生了负面倾向。而所谓“重启服务”的时间和频率也是由运营者决定，当遇到重大舆情时运营者也可以选择不重启或dump内存后重启。校园网流量日志的问题，对于不会使用代理的用户，实际上也没有很好的解决方案。**问题的关键从来不是技术。**

事实上，T大树洞也没有辜负过用户的信任，T大树洞团队一直严格按照树洞管理规范（试行）处理用户注册信息明文查询请求。在来自各方（如党委学生部、教职工、学生等）的查询请求中，我们拒绝了部分不满足管理规范的查询请求；对部分符合管理规范违规标准的严重越过红线的内容，我们对数据库中的用户注册邮箱密文尝试进行了解密，但**到目前为止我们还没有成功解密和对外公开过任何一位用户的邮箱明文**。事实上，**由于用户邮箱的构造实际上很不规则，暴力破解的难度是很大的**。

**Comment by hole-thu** [comment]
已经回应过了，**使用一个设计上比较安全的项目再去担心实际跑的代码不一致，也远好于使用一个设计上就直接不安全的项目**。不会有人因为担心telegram可能后台有鬼而认为telegram的安全性和微信没有区别。
另外后台匿名本身也是对运营者的保护（如果铁了心不打算出卖用户），这个问题希望T大树洞也认真思考一下。

关于你说的闭社的事情，链接我看了，没觉得有啥信誉问题，我观察到的多个平台上的清华学生也没啥负面看法。另外我们**只是使用闭社账户作为登陆认证，并不需要信任闭社**，具体细节可以阅读oauth的工作方式。新T树洞不会把安全性寄托在任何外部变量上。

**Comment by hole-thu** [comment]
> 在来自各方（如党委学生部、教职工、学生等）的查询请求中，我们拒绝了**部分**不满足管理规范的查询请求；对部分**符合管理规范违规标准的严重越过红线的内容**，我们对数据库中的用户注册邮箱密文**尝试进行了解密**，但到目前为止我们还没有成功解密和对外公开过任何一位用户的邮箱明文。事实上，由于用户邮箱的构造实际上很不规则，**暴力破解的难度是很大的**。

过于生草

**Comment by thuhole** [comment]
此issue正在指出，**newthuhole设计上的不安全性**。实际上，newthuhole在运营者匿名的情况下，所谓安全性、匿名性，**仍然完全是建立在用户的信任基础上的**，更不用说校园网流量日志的问题。我们无意将thuhole与newthuhole进行对比，也不想让树洞未来处于一个割裂状态。

有关闭社和oauth，此处的安全问题是在于我们无法确认闭社运营者和newthuhole运营者是否有联系，是否有个人或团体同时有这两个系统的管理权限和日志查看权限，在newthuhole运营者保持匿名的情况下，这一点永远无法被验证。

综上所述，如果从整体看，newthuhole相对thuhole对匿名性的改进，从技术角度看，实际微乎其微，仍然是完全建立在用户的信任基础上。

**Comment by thuhole** [comment]
林子大了什么鸟都有，管理问题实际上才是树洞面临的核心问题，越强匿名性只会越放大生活中人性中不光彩的一面。

**Comment by thuhole** [comment]
我相信你应该同意树洞的存在是为了提供自由、包容、开放的社交环境，而T大树洞合理的删帖尺度和各类tag已经获得了用户的认可。更强的匿名性和放任自由，也许只会带来更多恶意和违法的言论。

**Comment by hole-thu** [comment]
设计安全性指按照代码本身是否安全。实际运行的代码是否是开源代码需要用户自己选择是否信任。

> **另外后台匿名本身也是对运营者的保护**

不想追求匿名可以不做树洞，我自己也是闭社用户，不追求匿名的话闭社挺好的。新T树洞的最终目的是使用activitypub协议打造分布式互联的清华树洞族，以保证树洞永远不死，欢迎T大树洞加入。

重复内容不再回复了。

**Comment by thuhole** [comment]
实际上，从密码学来讲，设计安全性是包括信任问题的。不然像[微软零信任](https://www.microsoft.com/zh-cn/security/business/zero-trust)这样的设计就不算设计了？

运营者保护自身有很多方法，这个point有些跑题。

重复内容不回复，我想只是因为还没能给出一个有说服力的解释吧。

**Comment by thuhole** [comment]
有关“树洞永远不死”，我想Python和Go的AGPL v3协议的树洞后端代码就已经可以保证。还是那句话，不是技术问题。

**Comment by thuhole** [comment]
另外，从issue一开始就多次提到的newthuhole运营层与闭社运营层的关系的问题，一直被回避，我不想做过多揣测。我想这也是“设计安全性”的重要一部分吧？

**Comment by thuhole** [comment]
从设计安全性来讲，树洞其实也可以使用serverless设计，比如使用GitHub issues和GitHub API当数据库，所有事务处理全在前端使用javascript完成，这样就不牵扯到对运营者的信任的问题了。

这个案例旨在说明，所谓“设计安全性”，newthuhole还有很大提升空间。给软件的安全性盖一个“安全”或“不安全”的0 or 1的大帽子，是否有欠妥之处？

**Comment by hole-thu** [comment]
telegram和matrix在消息安全性上没有本质区别，开启端对端加密以后都可以视作安全的。用户信息安全性、未加密信息安全性取决于你更信任tg还是matrix服务器的运营着。

“树洞永远不死”指的是内容和存在性都一直延续，并且避免割裂用户，不是简单的可复制。


> 使用闭社帐号而非清华邮箱注册保证了即使在“哪些人注册了树洞”这个问题上新T树洞也有大于等于T大树洞的匿名性。

如果你不信任这里就取等于吧。


> 另外后台匿名本身也是对运营者的保护

我看不出T大树洞的运营者在被抓住以后有什么理由不交出数据。说自己把salt忘了？当然，从用户协议看T大树洞似乎也没打算完全保护用户信息。


“重复内容不再回复”是对后面可能出现的内容说的，不过你如果觉得还有什么未回答的可以列在这里，交给看官吧。

**Comment by thuhole** [comment]
那么，newthuhole的运营者在被抓住以后有什么理由不在后台安装日志记录软件呢？

**Comment by thuhole** [comment]
telegram的E2EE加密只是一小部分功能，对于群聊安全性，telegram是没有相关技术保证的。

**Comment by thuhole** [comment]
另外，如果你希望T大树洞加入树洞族计划，欢迎pull request，考虑merge。

**Comment by thuhole** [comment]
有关salt的问题，T大树洞的salt是一段很长的、随机生成的密钥。除了存在在某个境外服务器内存之外，只有一个在永久离线的可随时销毁的设备上的备份。newthuhole在防胁迫安全性上，并没有提升。都只能保证胁迫后的backward secrecy而不能保证胁迫的forward secrecy。

**Comment by thuhole** [comment]
总体来说，newthuhole无疑在设计上对匿名性的保证有提升，这是显然的事实。但是提升十分有限，而且实际上还有巨大的提升空间。

比如，至少新加入thuhole和/或未名BBS的登录方式，才能稍微减轻用户对于运营者身份的隐私顾虑。从利益角度来讲，也许newthuhole和闭社能有互相增进宣传、互相引流的关系，在没有任何方法验证身份的前提下，更会增加可疑程度。

**Comment by thuhole** [comment]
综上所述，这条issue已经指出了许多关键的点论证，虽然newthuhole相对thuhole对匿名性有提升，但提升非常有限，并且与thuhole一样，仍然主要依赖于用户对运营者的信任。在胁迫安全性上，也没有任何提升。

最后，非常欢迎给thuhole pull request。

**Comment by hole-thu** [comment]
> 那么，newthuhole的运营者在被抓住以后有什么理由不在后台安装日志记录软件呢？

当然，你当然可以把**后台实名的情况下拒绝交出之前的数据**的难度说得跟**后台匿名的情况下拒绝之后配合钓鱼**的难度说成一样的，就像你一直要把**设计上就后台实名**的安全性跟**设计上后台匿名但难以验证实际跑的代码与公布的一致**的安全性说成是一样的。总之你开心就好。

serverless... 我也不知道是在阴阳怪气还是真蠢。太恰到好处了。

总之issue区是给项目提建议的地方，如果你更喜欢吵架和自说自话，或许应该去更合适的地方。

> 至少新加入thuhole和/或未名BBS的登录方式

不难发现本项目从一开始就给thuhole和未名BBS在前端留了按钮，后端留了接口。`/_auth`接口的p参数就是指定身份验证的提供方。现在的主要问题是thuhole和未名BBS并没有任何身份验证接口。如果thuhole提供OpenId或者至少OAuth的话，我很乐意使用。

**Comment by thuhole** [comment]
issue是给本项目提建议的地方，不是吵架的地方。此issue一开始提出一个关于此项目可以改进的建议，却不知道是谁一直在讨论“一个设计上就直接不安全的项目”。

**Comment by thuhole** [comment]
此issue是在讨论本项目，而不是其他项目。此issue尝试指出，新T树洞的匿名性仍然需要基于对运营者的信任、用户对自己IP地址的隐藏、运营者必须不被胁迫、运营者与相关OAuth登录网站的私人关系。但是却总被项目作者newthuhole带偏到讨论另一个项目。

**Comment by thuhole** [comment]
总结一下，新T树洞的匿名性要求以下前置假设全部同时满足：
- 运营者不保留nginx或其他反代软件的日志（值得怀疑）
- 用户必须使用代理访问
- 运营者没有处于被胁迫的状态
- 运营者无权查看登录接口的日志

希望作者正面回应这4点。

**Comment by hole-thu** [comment]
> 但不管怎么说，使用一个设计上比较安全的项目再去担心实际跑的代码不一致，也远好于使用一个设计上就直接不安全的项目。

结合上下文这句话明显是在说 即使用户无法验证实际代码是否一致，后台匿名的设计也是有价值的，也是明显好于不这么做的。我说的时候也没想到后半句会被直接代入、当成特指某项目。

可能thuhole同学还是对自己的项目太在意了吧。

**Comment by thuhole** [comment]
很明显，此issue并没有否定此项目的意义和价值，为什么hole-thu同学这么敏感呢？

**Comment by hole-thu** [comment]
> 希望作者正面回应这4点。

thuhole同学对匿名性的定义似乎是，即使树洞是个一心要偷数据的钓鱼网站，并且全知全能地能掌握互联网上的一切数据，用户仍然可以正常使用不会暴露身份/泄露信息。
那么好的，新T树洞当然不是匿名的。

**Comment by thuhole** [comment]
很明显，有权限查看闭社登录接口的日志和闭社的用户信息，算不上是“全知全能地能掌握互联网上的一切数据”。nginx日志没关，也不太像是“一心要偷数据的钓鱼网站”。

**Comment by hole-thu** [comment]
> 有权限查看闭社登录接口的日志和闭社的用户信息

之前已经说过了，不管看不看闭社的用户信息，只要拿到闭社id已经**本质**实名了。新T树洞的匿名体现在从发布的内容并不能推出用户名。

> apache日志没关

新T树洞已经修复了把token放进url的糟糕设计。如果还要专门该日志配置，记录下header中的user_token这个敏感信息，显然是充满恶意的钓鱼网站了。

**Comment by hole-thu** [comment]
这是目前新T树洞的安全性标准

+ 对于普通使用：在后台不前置作恶（例如运行不一致的代码）的情况下，无法获取发言者身份

+ 对于临时token：在任意情况下（可以假设这是一个充满恶意的钓鱼网站、任何信息都是虚假的、拥有极大算力、掌握极多信息）无法获取发言者身份

**Comment by hole-thu** [comment]
![](https://user-images.githubusercontent.com/70618776/92588216-3e8e0880-f2cb-11ea-82a9-f1e04ea8404f.png)

**Comment by thuhole** [comment]
是否改了日志配置是**用户永远不可能知道的**，而且成本很低。如果你不知道怎么改，可以查看[这里](https://stackoverflow.com/questions/9948064/is-it-possible-to-log-all-http-request-headers-with-apache)，所以其实还是依赖于用户的信任。

临时token的设计，在记录日志且访问量不大的情况下，仍然没有匿名意义。

即便用户访问量很大（例如15分钟内上百人），临时token起效果还需要要求用户获取token后使用完全不同的IP、User Agent对树洞进行访问（否则在日志中检查15分钟内相同IP的访问记录即可）。而新T树洞并没有提供这样一个可以变更IP的客户端，默认的网页版客户端无法实现临时token所带来的匿名特性，反而临时token的按钮会引发虚假匿名的嫌疑。

最后，关于你这张图片的内容，我想看客都会有自己的判断，很多也是此issue内讨论过的问题。我就提一点，关于图片里最后一行，你已经是实名了，而且在公开信息中就可以通过技术手段找到证据，祝你好运。

**Comment by thuhole** [comment]
把token从url中放进header里的这个“修复”，不如说是在掩耳盗铃。

**Comment by hole-thu** [comment]
> 把token从url中放进header里的这个“修复”，不如说是在掩耳盗铃。

原来按照通用标准把token放在header里是掩耳盗铃，那么想必像T大树洞那样把token放在url里，让它在各种日志(甚至CDN的日志、安全防护工具的日志)里满天飞反倒是正确的了？不过从thuhole同学的一些过往行为看，好像很享受在日志里看用户的token嘛。
专门改日志去记录token这样的敏感信息当然是充满恶意的钓鱼行为，和偷偷跑一个不一致的后端无论性质上还是难度上都没有任何区别，不清楚thuhole同学为什么会觉得有特殊性。
关于“无前置作恶下的安全性”以及保障这种安全性能带来的好处，前面已经说了很多了。**如果当初T大树洞了提供了无前置作恶下的安全性，根本就不会出现如今一边出卖用户一边还有脸继续运营的局面了。**

> 临时token的设计，在记录日志且访问量不大的情况下，仍然没有匿名意义。

已经拿用户少说事了，thuhole同学是不是也承认自己找不到临时token在安全性上的漏洞呢？如果按这种攻击逻辑，干脆说，如果新T树洞用户少，无论怎么匿名都没有意义，因为反正发言者肯定是那么几个用户之一嘛。

-------------------------

顺便一提，**thuhole同学某天夜里在树洞上装成“懂网络技术”的路人，用看似两边都踩的话术强行把新T树洞的安全性说成和T大树洞是一样的，以及歪曲新T树洞的安全机制**，可以说是很无聊了。不过下次干这种事情记得做好伪装啊，thuhole同学是不是忘了自己在树洞置顶、github、tg群已经实名说过很多话了，还敢装路人长篇大论？扔进去训练个语言风格向量一下就判断出来了。甚至哪怕手动比对一下相同的语言习惯和结构，相同的攻击思路，完全一致的小细节错误，也能验证是同一人。

至于这段长篇大论本身，又是和之前的所谓“五重防护”一样在堆砌名词骗小白了。thuhole同学照搬自己如何偷用户邮箱的经验，臆想了一段新T树洞也这样根据token第一次出现附近的日志（甚至还要对比两边的日志）去偷用户的闭社id。然而哪怕认真看一下代码，或者听我的建议去了解一下oauth，也断不至于闹出这样的笑话。在新T树洞，用户的闭社id(或者T大树洞评论区代号)本就大大方方地记录在用户名里，哪里需要像做贼一样去偷呢？oauth的过程，本来就是申请权限查看闭社帐户信息。
之前已经说过了，甚至放进登陆框的提示了，新T树洞的安全性来自隔离用户和发布的内容，而非隔离用户和真人。实际上，作为一个需要限制清华同学使用且需要一人一号的平台，想隔离用户和真人是非常不切实际的，T大树洞做个哈希就宣称自己的匿名了，这才真正的掩耳盗铃吧。不管闭社id还是T大树洞评论区代号，都已经**本质**实名了，我是不是闭社管理员跟新T树洞是否安全又有什么关系呢(不过我确实不是)。如果我落进圈套，认真纠结于“**证明**自己不是谁”，那离“暴露自己是谁”也就不远了。

这段话没攻击到新T树洞什么，**倒是暴露了T大树洞一直在根据日志偷用户的邮箱**，我想这或许也是为什么thuhole同学一直对该如何正确枚举清华邮箱不感兴趣吧，毕竟根本不需要。**T大树洞在用户点下登陆按钮的时候，邮箱也会直接被放进url里(而非任何正常设计都会放进的body里)，在各种日志里满天飞**，不知道这是不是thuhole同学为了方便看日志有意为之的呢？此外，评论区里thuhole同学还暴露出了“面前有100块钱伸手就可以捡(偷)，别告诉我有人不会捡”的可怕三观。

前几天吹“自己没辜负信任”，暴露了已经在出卖用户，把之前承诺的一旦尝试解密不管成没成功都会告知、停机维护、重置所有人哈希当屁放掉了；这次装路人抹黑新树洞又暴露了自己早就在收集邮箱。thuhole同学还真是要注意祸从口出啊。
另一件有趣的事情是，thuhole同学宣称新T树洞虚假宣传，可是怎么至今没指出新T树洞的宣传里有具体哪一句话说得不对呢？实际上，已经有很多人诟病T大树洞极不安全了，这既有设计上的原因也有运营者态度的原因。要做到安全性显著高于T大树洞，既不是什么难事也不是什么高标准。

安全性和对安全性的虚假宣传一直是T大树洞最大的问题，也已经有很多人被安全性问题吓走了，我想这也是为什么thuhole同学看到出现一个安全性有显著提升的替代品（其实新T树洞在功能上也有显著提升）表现出这么地“**急了急了**”（其实新T树洞在功能上也有显著提升），又是在github上打滚，搞出新树洞和闭社是同一家CDN就“可能导致匿名性的彻底实(失)效”、”匿名性对相关CDN服务商是不存在的”、“newthuhole的运营者在被抓住以后有什么理由不在后台安装日志记录软件呢”等神论，转移重点试图猜测或者排除新T树洞的作者；又是在自己的平台上自导自演装路人抹黑新T树洞、宣扬新树洞更不安全，甚至秒删出现了对自己不利截图的洞；一面用不支持T大树洞帐号登陆攻击新洞，一面真要支持了又百般阻碍。

也观察thuhole君一段时间了，看得出来thuhole君很享受在自己的地盘上当上帝，很享受高度介入其他人的使用，享受其他人都求自己或者夸自己。喜欢的人觉得是负责、可爱，不喜欢的人觉得是滥权、中二。但不管怎么说，这是thuhole君自己的运营方式吧，我也没什么好过多评价的。结合看到的thuhole君某社交帐号的热度，我**完全理解**thuhole君非常珍惜，也非常害怕失去这种享受，这种之前可能从来没有体会过的存在感。但如果这种珍惜不是体现在提升自己的产品，解决的自己的问题，而是体现在掩盖问题、欺骗用户，甚至不择手段抹黑做得比自己更好的，那我只好祝thuhole君就一条道走到黑吧。

**Comment by thuhole** [comment]
如果你觉得某“懂网络技术”的路人是T大树洞运营团队的内部成员的话，那你可能对自己对语言习惯和结构的认知太过自信了。您有这时间对线，不如先仔细想想自己哪里暴露实名了。

如果有谁“急了”，从您这么长篇大论的回复来看，只能是指您自己吧？

看到你已经气急败坏了，而且发言逐渐向极端幼稚的方向发展，这个issue也就可以close了。

我们祝愿闭社和新T树洞越办越好！
在搜索引擎上看到了你的照片，你还是有点帅的。
最后，你们闭社的创业计划怎么样了？

**Comment by hole-thu** [comment]
数据不会骗人，只要你别删那个洞，任何人都可以自己跑一下验证嘛。
到底谁慌了不是很显然吗。祝thuhole君继续天天偷窥用户邮箱偷窥到爽哦。

（顺便，你说的照片应该是那位的，看他之前发文警告的语气...希望他不要摸到这里来吧哈哈哈哈）

**Comment by thuhole** [comment]
我说的那位不是你说的那位。
